"""Client onboarding — the second thing nothing else does.

Every comparable project stops at "the server is up". None of them solve *"run
this on the second laptop and its coding CLI is now pointed at the box in the
study, with its own key."* This module generates that config.

Which client to use is **conditional on the model**, per docs/DECISIONS.md §6:

* a tool-call-trained model  -> **Cline** (targeted edits, ~250 output tokens)
* a general model            -> **Aider** (no tool schemas, 1,024-token repo map)
* want one client for either -> **Octofriend** (ships repair models for both
  malformed tool calls *and* near-miss diffs)

Note the base-URL asymmetry: OpenAI-compatible clients want the `/v1` suffix,
Octofriend wants the bare origin. Getting that wrong is a silent 404.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from pathlib import Path

SUPPORTED = ("cline", "aider", "octofriend")


@dataclass
class ClientConfig:
    client: str
    filename: str
    content: str
    env: dict[str, str] = field(default_factory=dict)
    notes: list[str] = field(default_factory=list)
    extra_files: dict[str, str] = field(default_factory=dict)
    """Additional files this client needs, keyed by filename."""

    def write(self, directory: Path | str) -> Path:
        d = Path(directory)
        d.mkdir(parents=True, exist_ok=True)
        path = d / self.filename
        path.write_text(self.content, encoding="utf-8")
        for name, body in self.extra_files.items():
            (d / name).write_text(body, encoding="utf-8")
        return path


def normalise_base_url(url: str, *, want_v1: bool) -> str:
    """llama-server serves OpenAI routes under /v1; Octofriend wants the origin."""
    trimmed = url.rstrip("/")
    if trimmed.endswith("/v1"):
        trimmed = trimmed[: -len("/v1")]
    return f"{trimmed}/v1" if want_v1 else trimmed


def _cline(base_url: str, api_key: str, model: str, context: int) -> ClientConfig:
    settings = {
        "apiProvider": "openai-compatible",
        "openAiBaseUrl": normalise_base_url(base_url, want_v1=True),
        "openAiApiKey": api_key,
        "openAiModelId": model,
        "openAiModelInfo": {
            # Pin to the REAL per-slot budget. If Cline assumes more context than
            # the slot actually has, it will overflow and the server truncates.
            "contextWindow": context,
            "maxTokens": 4096,
            "supportsComputerUse": True,
        },
    }
    return ClientConfig(
        client="cline",
        filename="cline-settings.json",
        content=json.dumps(settings, indent=2) + "\n",
        notes=[
            "Paste into Cline's settings (gear icon) or ~/.cline/settings.json.",
            f"contextWindow is pinned to {context:,} - the real per-slot budget, not the "
            "model's advertised maximum.",
        ],
    )


def _aider(base_url: str, api_key: str, model: str, context: int) -> ClientConfig:
    conf = "\n".join(
        [
            "# generated by localllm",
            f"model: openai/{model}",
            "edit-format: diff",
            "map-tokens: 1024",
            "auto-commits: false",
            "model-metadata-file: .aider.model.metadata.json",
            "",
        ]
    )
    # Aider does not know a self-hosted model's limits, and without this it will
    # happily send more than the slot holds and be silently truncated server-side.
    metadata = {
        f"openai/{model}": {
            "max_input_tokens": context,
            "max_output_tokens": 4096,
            "litellm_provider": "openai",
            "mode": "chat",
        }
    }
    return ClientConfig(
        client="aider",
        filename=".aider.conf.yml",
        content=conf,
        env={
            "OPENAI_API_BASE": normalise_base_url(base_url, want_v1=True),
            "OPENAI_API_KEY": api_key,
        },
        extra_files={".aider.model.metadata.json": json.dumps(metadata, indent=2) + "\n"},
        notes=[
            "Install with: py -3.12 -m pip install aider-install && aider-install "
            "(Python 3.12, NOT 3.13+).",
            f"max_input_tokens is pinned to {context:,} so Aider respects the real per-slot "
            "budget instead of guessing.",
            "Use /add and /drop to control context; /clear between tasks.",
            "Switch to --edit-format whole for files under ~120 lines: it roughly doubles "
            "edit reliability, but costs ~10x the decode time on larger files.",
            "Avoid --architect; it doubles prefill.",
        ],
    )


def _octofriend(base_url: str, api_key: str, model: str, context: int) -> ClientConfig:
    origin = normalise_base_url(base_url, want_v1=False)
    body = "\n".join(
        [
            "// generated by localllm",
            "{",
            "  models: [",
            "    {",
            f'      nickname: "{model} (localllm)",',
            f'      baseUrl: "{origin}",',
            '      apiEnvVar: "LOCAL_LLM_KEY",',
            f'      model: "{model}",',
            f"      context: {context},",
            "    },",
            "  ],",
            "}",
            "",
        ]
    )
    return ClientConfig(
        client="octofriend",
        filename="octofriend.json5",
        content=body,
        env={"LOCAL_LLM_KEY": api_key},
        notes=[
            "Place at ~/.config/octofriend/octofriend.json5.",
            "Its fix-json and diff-apply repair models run locally on this laptop "
            "(CPU is fine) and auto-repair malformed tool calls and near-miss edits.",
            "OCTO_VERBOSE=1 surfaces raw tool-call errors.",
        ],
    )


_BUILDERS = {"cline": _cline, "aider": _aider, "octofriend": _octofriend}


def build_client_config(
    client: str,
    base_url: str,
    api_key: str,
    model: str,
    context: int,
) -> ClientConfig:
    key = client.lower()
    if key not in _BUILDERS:
        raise ValueError(f"unsupported client {client!r}; expected one of {', '.join(SUPPORTED)}")
    if not api_key:
        raise ValueError("an API key is required - issue one with `localllm key add <device>`")
    if context <= 0:
        raise ValueError("context must be positive")
    return _BUILDERS[key](base_url, api_key, model, context)


def recommend_client(*, model_is_tool_call_trained: bool) -> str:
    """DECISIONS.md §6: the right harness depends on how the model was trained."""
    return "cline" if model_is_tool_call_trained else "aider"
