"""Client onboarding — the second thing nothing else does.

Every comparable project stops at "the server is up". None of them solve *"run
this on the second laptop and its coding CLI is now pointed at the box in the
study, with its own key."* This module generates that config.

Which client to use is **conditional on the model**, per docs/DECISIONS.md §6:

* a tool-call-trained model  -> **Cline** (targeted edits, ~250 output tokens)
* a general model            -> **Aider** (no tool schemas, 1,024-token repo map)
* want one client for either -> **Octofriend** (ships repair models for both
  malformed tool calls *and* near-miss diffs)

Note the base-URL asymmetry: OpenAI-compatible clients want the `/v1` suffix,
Octofriend wants the bare origin. Getting that wrong is a silent 404.
"""

from __future__ import annotations

import json
import os
import re
from dataclasses import dataclass, field
from pathlib import Path

SUPPORTED = ("opencode", "continue", "aider", "octofriend", "qwen", "cline")

SIDECAR = "localllm-client.json"
"""Where `join` records what it configured, in one place for every client.

The three clients keep their settings in three shapes, and two of them put the
base URL in an *environment variable* rather than a file. So reading a client's
own config back is not enough to know where it points: on a fresh shell, Aider's
`.aider.conf.yml` names a model and nothing else.

This file closes that hole. It holds no secret — the key stays in the client's
own file or in the environment, exactly where the client itself looks for it.
"""

SIDECAR_VERSION = 1


@dataclass
class ClientConfig:
    client: str
    filename: str
    content: str
    env: dict[str, str] = field(default_factory=dict)
    notes: list[str] = field(default_factory=list)
    extra_files: dict[str, str] = field(default_factory=dict)
    """Additional files this client needs, keyed by filename."""

    key_env_var: str = ""
    """The variable this client reads its key from, when it is not in the file."""

    MARKER = "generated by localllm"
    """Written into the files whose format has comments, so a re-run can tell
    its own output from yours."""

    def sidecar(self, base_url: str, model: str, context: int) -> str:
        """What was configured, in a form every client shares."""
        return (
            json.dumps(
                {
                    "version": SIDECAR_VERSION,
                    "client": self.client,
                    "base_url": normalise_base_url(base_url, want_v1=False),
                    "model": model,
                    "context": context,
                    "key_env_var": self.key_env_var,
                },
                indent=2,
            )
            + "\n"
        )

    def write(self, directory: Path | str, *, force: bool = False) -> Path:
        """Write the config, refusing to clobber a file we did not write.

        Two of these filenames are `config.yaml` and `settings.json`, because
        that is what Continue and Qwen Code require. They are also two of the
        most common filenames in any project directory, so `join --client
        continue` run in the wrong folder would silently overwrite something
        unrelated and unrecoverable.

        Only those generic names are guarded. `octofriend.json5` and
        `.aider.conf.yml` collide with nothing, and refusing to overwrite them
        would break the ordinary case of re-running `join` after rotating a key.
        """
        d = Path(directory)
        d.mkdir(parents=True, exist_ok=True)
        planned = {self.filename: self.content, **self.extra_files}
        for name in planned:
            target = d / name
            if not force and name in GENERIC_FILENAMES and target.exists():
                if not _looks_like_ours(name, target):
                    raise FileExistsError(
                        f"{target} already exists and does not look like a "
                        f"localllm config. Writing there would destroy it. Use "
                        f"--out <dir> to put the config somewhere else, or "
                        f"--force to overwrite it anyway."
                    )
        for name, body in planned.items():
            (d / name).write_text(body, encoding="utf-8")
        return d / self.filename


GENERIC_FILENAMES = frozenset({"config.yaml", "settings.json"})
"""Filenames a client requires that are also common in unrelated projects."""


def _looks_like_ours(name: str, path: Path) -> bool:
    """Is this file one we could have written, or someone else's entirely?

    Two independent signals, because neither covers both formats: YAML carries
    our comment marker, and JSON cannot, so JSON is identified by whether the
    reader for that filename recognises its shape.
    """
    try:
        head = path.read_text(encoding="utf-8", errors="replace")[:4096]
    except OSError:
        return False
    if ClientConfig.MARKER in head:
        return True
    reader = dict(_READERS).get(name)
    return reader is not None and reader(path) is not None


def normalise_base_url(url: str, *, want_v1: bool) -> str:
    """llama-server serves OpenAI routes under /v1; Octofriend wants the origin."""
    trimmed = url.rstrip("/")
    if trimmed.endswith("/v1"):
        trimmed = trimmed[: -len("/v1")]
    return f"{trimmed}/v1" if want_v1 else trimmed


def _cline(base_url: str, api_key: str, model: str, context: int) -> ClientConfig:
    """Cline cannot be configured by writing a file, so this writes instructions.

    🚨 This used to emit `cline-settings.json` and tell the user to drop it at
    `~/.cline/settings.json`. There is no such file. Reading Cline's source
    (`apps/vscode/src/core/storage/state-migrations.ts`) shows settings go to
    VS Code's own `context.globalState` - a SQLite database VS Code holds open
    and caches in memory - and the API key to `context.secrets`, which is
    OS-encrypted (DPAPI on Windows). Neither can be written from outside.

    Worse, the field names it wrote are the *legacy* ones. Cline now scopes
    them per mode (`apps/vscode/src/shared/storage/state-keys.ts`):
    `planModeOpenAiModelId` / `actModeOpenAiModelId`, and the same for
    `ApiProvider` and `OpenAiModelInfo`. Only `openAiBaseUrl` is still flat.
    The old names survive solely in the migration list.

    So the honest output is the values to type and where to type them. Roo Code
    and Kilo Code are forks of this and inherit the same storage model.
    """
    v1 = normalise_base_url(base_url, want_v1=True)
    body = "\n".join(
        [
            "# Cline setup (generated by localllm)",
            "",
            "Cline keeps its settings in VS Code's own storage, not in a file:",
            "settings go to `globalState` (a SQLite database VS Code holds open)",
            "and the API key to the OS keychain. Nothing outside VS Code can write",
            "them, so these are values to enter, not a file to copy.",
            "",
            "Open Cline -> the gear icon -> API Provider, and set:",
            "",
            "| Field          | Value |",
            "|----------------|-------|",
            "| API Provider   | OpenAI Compatible |",
            f"| Base URL       | `{v1}` |",
            f"| API Key        | `{api_key}` |",
            f"| Model ID       | `{model}` |",
            f"| Context Window | `{context}` |",
            "| Max Output     | `4096` |",
            "",
            f"Set the context window to {context:,} in **both** Plan and Act modes.",
            "Cline stores them separately (`planModeOpenAiModelInfo` and",
            "`actModeOpenAiModelInfo`), so setting one leaves the other guessing -",
            "and a client that assumes more context than the slot has will overflow",
            "it and be silently truncated server-side.",
            "",
            "Prefer a client that can be configured from here? `--client opencode`",
            "or `--client continue` write a real config file.",
            "",
        ]
    )
    return ClientConfig(
        client="cline",
        filename="cline-setup.md",
        content=body,
        notes=[
            "Install with: code --install-extension saoudrizwan.claude-dev",
            "This file is INSTRUCTIONS, not a config - Cline reads its settings from "
            "VS Code's SQLite storage and the OS keychain, which cannot be written "
            "from outside VS Code.",
            f"Enter the {context:,} context window in both Plan and Act mode.",
        ],
    )


def _opencode(base_url: str, api_key: str, model: str, context: int) -> ClientConfig:
    """opencode ships a documented llama.cpp provider block, and pins context.

    `limit.context` is not decoration. opencode uses it to know how much of the
    window is left and when to compact; for a local model models.dev has no
    entry to fall back on, so leaving it out means the client never compacts
    and overruns the slot.
    """
    settings = {
        "$schema": "https://opencode.ai/config.json",
        "provider": {
            "llama.cpp": {
                # openai-compatible, NOT openai: the latter targets /v1/responses,
                # which llama-server does not serve.
                "npm": "@ai-sdk/openai-compatible",
                "name": "llama-server (localllm)",
                "options": {
                    "baseURL": normalise_base_url(base_url, want_v1=True),
                    "apiKey": "{env:LOCAL_LLM_KEY}",
                },
                "models": {
                    model: {
                        "name": f"{model} (localllm)",
                        "limit": {"context": context, "output": 4096},
                    }
                },
            }
        },
        "model": f"llama.cpp/{model}",
    }
    return ClientConfig(
        client="opencode",
        filename="opencode.json",
        content=json.dumps(settings, indent=2) + "\n",
        env={"LOCAL_LLM_KEY": api_key},
        key_env_var="LOCAL_LLM_KEY",
        notes=[
            "Install with: npm install -g opencode-ai",
            "Global config path: %USERPROFILE%\\.config\\opencode\\opencode.json "
            "(opencode uses XDG paths on Windows too). Or leave this file in a "
            "project root, which takes precedence.",
            f"limit.context is pinned to {context:,} so opencode compacts before "
            "it overruns the slot instead of after.",
            "limit.output is capped at 4,096 so one reply cannot spend the whole window.",
        ],
    )


def _continue(base_url: str, api_key: str, model: str, context: int) -> ClientConfig:
    """Continue's YAML config - the only VS Code extension here that has one.

    Two models on purpose. Autocomplete fires on nearly every keystroke, and
    over a LAN a full-context FIM request per keystroke is what makes a local
    model feel unusable; `maxPromptTokens: 1024` keeps those small while chat
    still gets the whole slot.
    """
    v1 = normalise_base_url(base_url, want_v1=True)
    body = "\n".join(
        [
            "# generated by localllm",
            "name: localllm",
            "version: 0.0.1",
            "schema: v1",
            "",
            "models:",
            f"  - name: {model} (localllm)",
            "    provider: openai",
            f"    model: {model}",
            f"    apiBase: {v1}",
            f"    apiKey: {api_key}",
            "    roles: [chat, edit, apply]",
            "    capabilities:",
            # Continue autodetects tool support from the provider and model NAME.
            # A self-hosted model is not in its table, so without this Agent mode
            # is silently unavailable rather than reported as unsupported.
            "      - tool_use",
            "    defaultCompletionOptions:",
            f"      contextLength: {context}",
            "      maxTokens: 4096",
            "",
            f"  - name: {model} (autocomplete)",
            "    provider: openai",
            f"    model: {model}",
            f"    apiBase: {v1}",
            f"    apiKey: {api_key}",
            # autocomplete is NOT in Continue's default role list, so a model
            # that does not name it is never asked for completions at all.
            "    roles: [autocomplete]",
            "    autocompleteOptions:",
            "      maxPromptTokens: 1024",
            "      debounceDelay: 350",
            "      onlyMyCode: true",
            "",
        ]
    )
    return ClientConfig(
        client="continue",
        filename="config.yaml",
        content=body,
        notes=[
            "Install with: code --install-extension Continue.continue",
            "Place at %USERPROFILE%\\.continue\\config.yaml. config.json is the "
            "deprecated format - this is the current one.",
            "capabilities: [tool_use] is set explicitly because Continue detects "
            "tool support from the model NAME, and a self-hosted model is not in "
            "its table - without it Agent mode silently does nothing.",
            f"Chat gets the full {context:,} tokens; autocomplete is capped at 1,024 "
            "so the every-keystroke requests stay small over the LAN.",
        ],
    )


def _qwen(base_url: str, api_key: str, model: str, context: int) -> ClientConfig:
    """Qwen Code's settings.json, configured non-interactively.

    `security.auth.selectedType` is what makes this zero-touch: without it the
    CLI stops on first run and asks the user to pick a provider through `/auth`.
    """
    provider_id = f"{model}-localllm"
    settings = {
        "modelProviders": {
            "openai": [
                {
                    "id": provider_id,
                    "name": f"{model} (localllm)",
                    "baseUrl": normalise_base_url(base_url, want_v1=True),
                    "description": "llama-server on the study laptop",
                    "envKey": "LOCAL_LLM_KEY",
                }
            ]
        },
        "security": {"auth": {"selectedType": "openai"}},
        "model": {"name": provider_id},
    }
    return ClientConfig(
        client="qwen",
        filename="settings.json",
        content=json.dumps(settings, indent=2) + "\n",
        env={"LOCAL_LLM_KEY": api_key},
        key_env_var="LOCAL_LLM_KEY",
        notes=[
            "Install with: npm install -g @qwen-code/qwen-code@latest (needs Node 22+)",
            "Place at %USERPROFILE%\\.qwen\\settings.json.",
            "security.auth.selectedType is set so the CLI does not stop and ask "
            "you to choose a provider on first run.",
            # Stated rather than guessed. Inventing a field name here would look
            # like the limit was applied while the client kept overrunning it.
            f"WARNING: Qwen Code has no verified way to pin the context window, so "
            f"it does not know about the {context:,}-token slot. Prompts longer than "
            f"that are truncated by the server, not refused by the client. Prefer "
            f"opencode or continue if that matters.",
        ],
    )


def _aider(base_url: str, api_key: str, model: str, context: int) -> ClientConfig:
    conf = "\n".join(
        [
            "# generated by localllm",
            f"model: openai/{model}",
            "edit-format: diff",
            "map-tokens: 1024",
            "auto-commits: false",
            "model-metadata-file: .aider.model.metadata.json",
            "",
        ]
    )
    # Aider does not know a self-hosted model's limits, and without this it will
    # happily send more than the slot holds and be silently truncated server-side.
    metadata = {
        f"openai/{model}": {
            "max_input_tokens": context,
            "max_output_tokens": 4096,
            "litellm_provider": "openai",
            "mode": "chat",
        }
    }
    return ClientConfig(
        client="aider",
        filename=".aider.conf.yml",
        content=conf,
        env={
            "OPENAI_API_BASE": normalise_base_url(base_url, want_v1=True),
            "OPENAI_API_KEY": api_key,
        },
        extra_files={".aider.model.metadata.json": json.dumps(metadata, indent=2) + "\n"},
        key_env_var="OPENAI_API_KEY",
        notes=[
            "Install with: py -3.12 -m pip install aider-install && aider-install "
            "(Python 3.12, NOT 3.13+).",
            f"max_input_tokens is pinned to {context:,} so Aider respects the real per-slot "
            "budget instead of guessing.",
            "Use /add and /drop to control context; /clear between tasks.",
            "Switch to --edit-format whole for files under ~120 lines: it roughly doubles "
            "edit reliability, but costs ~10x the decode time on larger files.",
            "Avoid --architect; it doubles prefill.",
        ],
    )


def _octofriend(base_url: str, api_key: str, model: str, context: int) -> ClientConfig:
    origin = normalise_base_url(base_url, want_v1=False)
    body = "\n".join(
        [
            "// generated by localllm",
            "{",
            "  models: [",
            "    {",
            f'      nickname: "{model} (localllm)",',
            f'      baseUrl: "{origin}",',
            '      apiEnvVar: "LOCAL_LLM_KEY",',
            f'      model: "{model}",',
            f"      context: {context},",
            "    },",
            "  ],",
            "}",
            "",
        ]
    )
    return ClientConfig(
        client="octofriend",
        filename="octofriend.json5",
        content=body,
        env={"LOCAL_LLM_KEY": api_key},
        key_env_var="LOCAL_LLM_KEY",
        notes=[
            "Place at ~/.config/octofriend/octofriend.json5.",
            "Its fix-json and diff-apply repair models run locally on this laptop "
            "(CPU is fine) and auto-repair malformed tool calls and near-miss edits.",
            "OCTO_VERBOSE=1 surfaces raw tool-call errors.",
        ],
    )


_BUILDERS = {
    "opencode": _opencode,
    "continue": _continue,
    "aider": _aider,
    "octofriend": _octofriend,
    "qwen": _qwen,
    "cline": _cline,
}


@dataclass(frozen=True)
class ClientProfile:
    """How to *get* a coding agent, not just how to configure one.

    `join` writes a config file, which is necessary and not sufficient: on a
    fresh laptop the agent it configures is not installed, and the two things
    that actually go wrong - no Node, no VS Code - surface as errors from the
    agent's own installer that mention nothing about this project.
    """

    name: str
    title: str
    install: str
    why: str
    requires: tuple[str, ...] = ()
    """Commands that must already be on PATH. Checked before anything is written."""

    join_name: str = ""
    """The config writer to use, when it differs from `name`."""

    writes_config: bool = True
    """False when the agent keeps its settings somewhere unwritable, so what
    `join` produces is instructions rather than configuration. Stated on the
    profile so the caller can say which it got."""

    free: bool = True

    def __post_init__(self) -> None:
        if not self.join_name:
            object.__setattr__(self, "join_name", self.name)


CLIENTS: dict[str, ClientProfile] = {
    p.name: p
    for p in (
        ClientProfile(
            name="opencode",
            title="opencode (terminal)",
            install="npm install -g opencode-ai",
            why="the only client here that both writes from a file and knows how "
            "much of the slot is left - it compacts before it overruns",
            requires=("node",),
            writes_config=True,
        ),
        ClientProfile(
            name="continue",
            title="Continue (VS Code)",
            install="code --install-extension Continue.continue",
            why="the one VS Code extension with a real config file, and it splits "
            "chat from autocomplete so the every-keystroke requests stay small",
            requires=("code",),
            writes_config=True,
        ),
        ClientProfile(
            name="aider",
            title="Aider (terminal)",
            install="py -3.12 -m pip install aider-install && aider-install",
            why="no tool schemas at all - the right choice for a model that was "
            "not trained to emit them",
            requires=(),
            writes_config=True,
        ),
        ClientProfile(
            name="octofriend",
            title="Octofriend (terminal)",
            install="npm install -g octofriend",
            why="ships local repair models for malformed tool calls and near-miss "
            "diffs, which is what low-bit quantisation breaks first",
            requires=("node",),
            writes_config=True,
        ),
        ClientProfile(
            name="qwen",
            title="Qwen Code (terminal)",
            install="npm install -g @qwen-code/qwen-code@latest",
            why="fully non-interactive setup, but it has no way to pin the context "
            "window, so it will overrun the slot and be truncated server-side",
            requires=("node",),
            writes_config=True,
        ),
        ClientProfile(
            name="cline",
            title="Cline (VS Code)",
            install="code --install-extension saoudrizwan.claude-dev",
            why="strong agent, but its settings live in VS Code's SQLite storage "
            "and the OS keychain - so the values have to be typed in by hand",
            requires=("code",),
            writes_config=False,
        ),
    )
}


def recommend_client_for(model: str) -> str:
    """Pick a harness from the model id, falling back when it says nothing.

    DECISIONS.md §6 makes this conditional on tool-call training, and the id is
    the only thing that answers it. Note what is *not* usable here: the model
    **alias** in an invite is the fixed value in `constants.MODEL_ALIAS`,
    chosen so Claude-compatible clients find it. Passing that in returns the
    fallback, which is the honest answer - a constant carries no information.

    Notably this never returns Cline, even though Cline is the better harness
    for a tool-call-trained model. Cline cannot be configured from a file, so
    recommending it from a command whose entire job is to write one produces a
    laptop that is set up everywhere except the place that matters.
    """
    lowered = model.lower()
    if any(m in lowered for m in ("gpt-oss", "kat-coder", "qwen3-coder", "qwen3.6")):
        return "opencode"
    if "qwen2.5-coder" in lowered:
        return "aider"
    return "octofriend"


def build_client_config(
    client: str,
    base_url: str,
    api_key: str,
    model: str,
    context: int,
) -> ClientConfig:
    key = client.lower()
    if key not in _BUILDERS:
        raise ValueError(f"unsupported client {client!r}; expected one of {', '.join(SUPPORTED)}")
    if not api_key:
        raise ValueError("an API key is required - issue one with `localllm key add <device>`")
    if context <= 0:
        raise ValueError("context must be positive")
    config = _BUILDERS[key](base_url, api_key, model, context)
    # Always alongside the client's own file, so the doctor can find out where
    # this laptop points without depending on the shell's environment.
    config.extra_files[SIDECAR] = config.sidecar(base_url, model, context)
    return config


def recommend_client(*, model_is_tool_call_trained: bool) -> str:
    """DECISIONS.md §6: the right harness depends on how the model was trained."""
    return "cline" if model_is_tool_call_trained else "aider"


# --- reading a config back ---------------------------------------------------


@dataclass(frozen=True)
class DiscoveredClient:
    """A client config found on disk, in the terms the doctor needs.

    `check` used to require the URL, key and model to be supplied again,
    moments after `join` had written all three to a file in the current
    directory. Retyping them is not just tedious - a typo in the retyped
    version gets diagnosed as a server fault, which is the opposite of what
    the doctor is for.
    """

    client: str
    path: Path
    base_url: str
    model: str
    api_key: str = ""
    context: int | None = None
    key_env_var: str = ""
    """Set when the key lives in the environment rather than the file, which is
    how Aider and Octofriend are configured. Naming it lets the doctor say
    which variable is unset instead of reporting a missing key."""

    drift: tuple[str, ...] = ()
    """Fields where the client's own config disagrees with what `join`
    recorded. Non-empty means someone edited the client file afterwards, and
    the values reported here are the client's — the ones it will actually
    send."""


def _read_cline(path: Path) -> DiscoveredClient | None:
    """Deliberately none. Cline's settings are not on disk in any readable form.

    This used to parse the `cline-settings.json` that `_cline` wrote - a file
    Cline itself never reads. Parsing it back reported the laptop as configured
    with values the extension had never seen, so `check` verified our own
    output rather than the client's state. Reporting nothing is correct: the
    sidecar records what was *intended*, and that is all this machine knows.
    """
    return None


def _read_opencode(path: Path) -> DiscoveredClient | None:
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return None
    providers = data.get("provider") if isinstance(data, dict) else None
    if not isinstance(providers, dict):
        return None
    for provider in providers.values():
        if not isinstance(provider, dict):
            continue
        options = provider.get("options")
        url = options.get("baseURL") if isinstance(options, dict) else None
        if not isinstance(url, str) or not url:
            continue
        models = provider.get("models")
        model, context = "", None
        if isinstance(models, dict) and models:
            model = str(next(iter(models)))
            entry = models[model]
            limit = entry.get("limit") if isinstance(entry, dict) else None
            value = limit.get("context") if isinstance(limit, dict) else None
            if isinstance(value, int) and not isinstance(value, bool):
                context = value
        raw_key = str((options or {}).get("apiKey") or "")
        env_var = ""
        match = re.fullmatch(r"\{env:([A-Za-z_][A-Za-z0-9_]*)\}", raw_key)
        if match:
            env_var = match.group(1)
        return DiscoveredClient(
            client="opencode",
            path=path,
            base_url=url,
            model=model,
            api_key=os.environ.get(env_var, "") if env_var else raw_key,
            context=context,
            key_env_var=env_var,
        )
    return None


def _read_continue(path: Path) -> DiscoveredClient | None:
    """A tolerant scan rather than a YAML parse.

    PyYAML is not a dependency of this project and adding one so that `check`
    can read a file it wrote itself is a poor trade. The fields wanted here are
    all `key: value` on their own line.
    """
    try:
        text = path.read_text(encoding="utf-8")
    except OSError:
        return None

    def first(pattern: str) -> str:
        match = re.search(pattern, text, re.MULTILINE)
        return match.group(1).strip() if match else ""

    url = first(r"^\s*apiBase:\s*(\S+)")
    if not url:
        return None
    context = first(r"^\s*contextLength:\s*(\d+)")
    return DiscoveredClient(
        client="continue",
        path=path,
        base_url=url,
        model=first(r"^\s*model:\s*(\S+)"),
        api_key=first(r"^\s*apiKey:\s*(\S+)"),
        context=int(context) if context else None,
    )


def _read_qwen(path: Path) -> DiscoveredClient | None:
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return None
    providers = data.get("modelProviders") if isinstance(data, dict) else None
    entries = providers.get("openai") if isinstance(providers, dict) else None
    if not isinstance(entries, list) or not entries:
        return None
    entry = entries[0]
    if not isinstance(entry, dict):
        return None
    url = entry.get("baseUrl")
    if not isinstance(url, str) or not url:
        return None
    env_var = str(entry.get("envKey") or "")
    return DiscoveredClient(
        client="qwen",
        path=path,
        base_url=url,
        model=str(entry.get("id") or ""),
        api_key=os.environ.get(env_var, "") if env_var else "",
        # Qwen Code has no verified context field, so there is nothing to read.
        # Reporting None means the sidecar's number is used unchallenged, which
        # is right: nothing here can contradict it.
        context=None,
        key_env_var=env_var,
    )


def _read_aider(path: Path) -> DiscoveredClient | None:
    """Aider splits itself across three places: the model in a YAML file, the
    limits in a metadata JSON, and the URL and key in the environment."""
    try:
        conf = path.read_text(encoding="utf-8")
    except OSError:
        return None
    model = ""
    for line in conf.splitlines():
        if line.strip().startswith("model:"):
            model = line.split(":", 1)[1].strip()
            break
    if not model:
        return None

    context = None
    meta_path = path.parent / ".aider.model.metadata.json"
    if meta_path.exists():
        try:
            meta = json.loads(meta_path.read_text(encoding="utf-8"))
            entry = meta.get(model) if isinstance(meta, dict) else None
            if isinstance(entry, dict):
                value = entry.get("max_input_tokens")
                if isinstance(value, int) and not isinstance(value, bool):
                    context = value
        except (OSError, ValueError):
            context = None

    return DiscoveredClient(
        client="aider",
        path=path,
        base_url=os.environ.get("OPENAI_API_BASE", ""),
        # Aider is told `openai/<model>`; the server knows it without the prefix.
        model=model.split("/", 1)[-1],
        api_key=os.environ.get("OPENAI_API_KEY", ""),
        context=context,
        key_env_var="OPENAI_API_KEY",
    )


def _read_octofriend(path: Path) -> DiscoveredClient | None:
    """JSON5: unquoted keys and trailing commas, so json.loads cannot be used.

    A tolerant field scan is deliberate - this file is meant to be hand-edited,
    and refusing to read a config a user has legitimately customised would send
    them back to retyping the very values we are trying to recover.
    """
    try:
        text = path.read_text(encoding="utf-8")
    except OSError:
        return None

    def field_of(name: str) -> str:
        match = re.search(rf'{name}\s*:\s*"([^"]*)"', text)
        return match.group(1) if match else ""

    url = field_of("baseUrl")
    if not url:
        return None
    context_match = re.search(r"context\s*:\s*(\d+)", text)
    env_var = field_of("apiEnvVar") or "LOCAL_LLM_KEY"
    return DiscoveredClient(
        client="octofriend",
        path=path,
        base_url=url,
        model=field_of("model"),
        api_key=os.environ.get(env_var, ""),
        context=int(context_match.group(1)) if context_match else None,
        key_env_var=env_var,
    )


_READERS = (
    ("opencode.json", _read_opencode),
    ("config.yaml", _read_continue),
    (".aider.conf.yml", _read_aider),
    ("octofriend.json5", _read_octofriend),
    ("settings.json", _read_qwen),
)


def _read_own_config(directory: Path) -> DiscoveredClient | None:
    """The first client config in this directory that parses.

    Split out rather than inlined so the file is read once per reader: the
    generator that replaced it evaluated the reader twice, once to test the
    result and once to yield it.
    """
    for filename, reader in _READERS:
        path = directory / filename
        if path.exists():
            found = reader(path)
            if found is not None:
                return found
    return None


def _read_sidecar(path: Path) -> DiscoveredClient | None:
    """The record `join` leaves, which every client shares.

    Preferred over the client's own file because two of the three keep their
    base URL in the environment: on a fresh shell those configs name a model
    and nothing else, which is not enough to check anything.
    """
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return None
    if not isinstance(data, dict) or data.get("version") != SIDECAR_VERSION:
        return None
    url = data.get("base_url")
    if not isinstance(url, str) or not url:
        return None

    client = str(data.get("client") or "")
    env_var = str(data.get("key_env_var") or "")
    # The secret deliberately is not here. It stays where the client itself
    # looks for it: in the client's own file, or in the environment.
    api_key = os.environ.get(env_var, "") if env_var else ""
    if not api_key:
        own = _read_own_config(path.parent)
        if own is not None:
            api_key = own.api_key

    context = data.get("context")
    return DiscoveredClient(
        client=client,
        path=path,
        base_url=url,
        model=str(data.get("model") or ""),
        api_key=api_key,
        context=context if isinstance(context, int) and not isinstance(context, bool) else None,
        key_env_var=env_var,
    )


def read_client_config(directory: Path | str = ".") -> DiscoveredClient | None:
    """Find a config this tool wrote and recover what the doctor needs.

    Returns None rather than raising: not finding one is an ordinary state on a
    laptop that has not been joined yet, and the caller has a better error to
    give than this function does.

    When both the sidecar and the client's own file are present they are
    **reconciled, and the client's file wins**. The sidecar records what `join`
    intended; the client file is what the client actually loads. Preferring the
    sidecar unconditionally meant a hand-edited `octofriend.json5` asking for
    131,072 tokens was checked as though it asked for 8,192 — so `check`
    reported "context agrees" for a client heading straight into a 400. Two
    copies of one fact, and nothing comparing them.
    """
    d = Path(directory)
    own = _read_own_config(d)

    sidecar = d / SIDECAR
    recorded = _read_sidecar(sidecar) if sidecar.exists() else None

    if recorded is None:
        # Covers a laptop joined before the sidecar existed, and one a user
        # assembled by hand.
        return own
    if own is None:
        return recorded

    drift = tuple(
        field
        for field, intended, actual in (
            ("context", recorded.context, own.context),
            ("model", recorded.model, own.model),
        )
        # A client file that does not carry a field at all is not disagreeing
        # about it; only a different value is drift.
        if actual is not None and actual != "" and intended != actual
    )
    if not drift:
        return recorded

    # Take the client's own values where it has them, but keep the sidecar's
    # base URL when the client keeps that in the environment and it is unset.
    return DiscoveredClient(
        client=own.client,
        path=own.path,
        base_url=own.base_url or recorded.base_url,
        model=own.model or recorded.model,
        api_key=own.api_key or recorded.api_key,
        context=own.context if own.context is not None else recorded.context,
        key_env_var=own.key_env_var or recorded.key_env_var,
        drift=drift,
    )
