"""Client onboarding — the second thing nothing else does.

Every comparable project stops at "the server is up". None of them solve *"run
this on the second laptop and its coding CLI is now pointed at the box in the
study, with its own key."* This module generates that config.

Which client to use is **conditional on the model**, per docs/DECISIONS.md §6:

* a tool-call-trained model  -> **Cline** (targeted edits, ~250 output tokens)
* a general model            -> **Aider** (no tool schemas, 1,024-token repo map)
* want one client for either -> **Octofriend** (ships repair models for both
  malformed tool calls *and* near-miss diffs)

Note the base-URL asymmetry: OpenAI-compatible clients want the `/v1` suffix,
Octofriend wants the bare origin. Getting that wrong is a silent 404.
"""

from __future__ import annotations

import json
import os
import re
from dataclasses import dataclass, field
from pathlib import Path

SUPPORTED = ("cline", "aider", "octofriend")

SIDECAR = "localllm-client.json"
"""Where `join` records what it configured, in one place for every client.

The three clients keep their settings in three shapes, and two of them put the
base URL in an *environment variable* rather than a file. So reading a client's
own config back is not enough to know where it points: on a fresh shell, Aider's
`.aider.conf.yml` names a model and nothing else.

This file closes that hole. It holds no secret — the key stays in the client's
own file or in the environment, exactly where the client itself looks for it.
"""

SIDECAR_VERSION = 1


@dataclass
class ClientConfig:
    client: str
    filename: str
    content: str
    env: dict[str, str] = field(default_factory=dict)
    notes: list[str] = field(default_factory=list)
    extra_files: dict[str, str] = field(default_factory=dict)
    """Additional files this client needs, keyed by filename."""

    key_env_var: str = ""
    """The variable this client reads its key from, when it is not in the file."""

    def sidecar(self, base_url: str, model: str, context: int) -> str:
        """What was configured, in a form every client shares."""
        return (
            json.dumps(
                {
                    "version": SIDECAR_VERSION,
                    "client": self.client,
                    "base_url": normalise_base_url(base_url, want_v1=False),
                    "model": model,
                    "context": context,
                    "key_env_var": self.key_env_var,
                },
                indent=2,
            )
            + "\n"
        )

    def write(self, directory: Path | str) -> Path:
        d = Path(directory)
        d.mkdir(parents=True, exist_ok=True)
        path = d / self.filename
        path.write_text(self.content, encoding="utf-8")
        for name, body in self.extra_files.items():
            (d / name).write_text(body, encoding="utf-8")
        return path


def normalise_base_url(url: str, *, want_v1: bool) -> str:
    """llama-server serves OpenAI routes under /v1; Octofriend wants the origin."""
    trimmed = url.rstrip("/")
    if trimmed.endswith("/v1"):
        trimmed = trimmed[: -len("/v1")]
    return f"{trimmed}/v1" if want_v1 else trimmed


def _cline(base_url: str, api_key: str, model: str, context: int) -> ClientConfig:
    settings = {
        "apiProvider": "openai-compatible",
        "openAiBaseUrl": normalise_base_url(base_url, want_v1=True),
        "openAiApiKey": api_key,
        "openAiModelId": model,
        "openAiModelInfo": {
            # Pin to the REAL per-slot budget. If Cline assumes more context than
            # the slot actually has, it will overflow and the server truncates.
            "contextWindow": context,
            "maxTokens": 4096,
            "supportsComputerUse": True,
        },
    }
    return ClientConfig(
        client="cline",
        filename="cline-settings.json",
        content=json.dumps(settings, indent=2) + "\n",
        notes=[
            "Paste into Cline's settings (gear icon) or ~/.cline/settings.json.",
            f"contextWindow is pinned to {context:,} - the real per-slot budget, not the "
            "model's advertised maximum.",
        ],
    )


def _aider(base_url: str, api_key: str, model: str, context: int) -> ClientConfig:
    conf = "\n".join(
        [
            "# generated by localllm",
            f"model: openai/{model}",
            "edit-format: diff",
            "map-tokens: 1024",
            "auto-commits: false",
            "model-metadata-file: .aider.model.metadata.json",
            "",
        ]
    )
    # Aider does not know a self-hosted model's limits, and without this it will
    # happily send more than the slot holds and be silently truncated server-side.
    metadata = {
        f"openai/{model}": {
            "max_input_tokens": context,
            "max_output_tokens": 4096,
            "litellm_provider": "openai",
            "mode": "chat",
        }
    }
    return ClientConfig(
        client="aider",
        filename=".aider.conf.yml",
        content=conf,
        env={
            "OPENAI_API_BASE": normalise_base_url(base_url, want_v1=True),
            "OPENAI_API_KEY": api_key,
        },
        extra_files={".aider.model.metadata.json": json.dumps(metadata, indent=2) + "\n"},
        key_env_var="OPENAI_API_KEY",
        notes=[
            "Install with: py -3.12 -m pip install aider-install && aider-install "
            "(Python 3.12, NOT 3.13+).",
            f"max_input_tokens is pinned to {context:,} so Aider respects the real per-slot "
            "budget instead of guessing.",
            "Use /add and /drop to control context; /clear between tasks.",
            "Switch to --edit-format whole for files under ~120 lines: it roughly doubles "
            "edit reliability, but costs ~10x the decode time on larger files.",
            "Avoid --architect; it doubles prefill.",
        ],
    )


def _octofriend(base_url: str, api_key: str, model: str, context: int) -> ClientConfig:
    origin = normalise_base_url(base_url, want_v1=False)
    body = "\n".join(
        [
            "// generated by localllm",
            "{",
            "  models: [",
            "    {",
            f'      nickname: "{model} (localllm)",',
            f'      baseUrl: "{origin}",',
            '      apiEnvVar: "LOCAL_LLM_KEY",',
            f'      model: "{model}",',
            f"      context: {context},",
            "    },",
            "  ],",
            "}",
            "",
        ]
    )
    return ClientConfig(
        client="octofriend",
        filename="octofriend.json5",
        content=body,
        env={"LOCAL_LLM_KEY": api_key},
        key_env_var="LOCAL_LLM_KEY",
        notes=[
            "Place at ~/.config/octofriend/octofriend.json5.",
            "Its fix-json and diff-apply repair models run locally on this laptop "
            "(CPU is fine) and auto-repair malformed tool calls and near-miss edits.",
            "OCTO_VERBOSE=1 surfaces raw tool-call errors.",
        ],
    )


_BUILDERS = {"cline": _cline, "aider": _aider, "octofriend": _octofriend}


def build_client_config(
    client: str,
    base_url: str,
    api_key: str,
    model: str,
    context: int,
) -> ClientConfig:
    key = client.lower()
    if key not in _BUILDERS:
        raise ValueError(f"unsupported client {client!r}; expected one of {', '.join(SUPPORTED)}")
    if not api_key:
        raise ValueError("an API key is required - issue one with `localllm key add <device>`")
    if context <= 0:
        raise ValueError("context must be positive")
    config = _BUILDERS[key](base_url, api_key, model, context)
    # Always alongside the client's own file, so the doctor can find out where
    # this laptop points without depending on the shell's environment.
    config.extra_files[SIDECAR] = config.sidecar(base_url, model, context)
    return config


def recommend_client(*, model_is_tool_call_trained: bool) -> str:
    """DECISIONS.md §6: the right harness depends on how the model was trained."""
    return "cline" if model_is_tool_call_trained else "aider"


# --- reading a config back ---------------------------------------------------


@dataclass(frozen=True)
class DiscoveredClient:
    """A client config found on disk, in the terms the doctor needs.

    `check` used to require the URL, key and model to be supplied again,
    moments after `join` had written all three to a file in the current
    directory. Retyping them is not just tedious - a typo in the retyped
    version gets diagnosed as a server fault, which is the opposite of what
    the doctor is for.
    """

    client: str
    path: Path
    base_url: str
    model: str
    api_key: str = ""
    context: int | None = None
    key_env_var: str = ""
    """Set when the key lives in the environment rather than the file, which is
    how Aider and Octofriend are configured. Naming it lets the doctor say
    which variable is unset instead of reporting a missing key."""

    drift: tuple[str, ...] = ()
    """Fields where the client's own config disagrees with what `join`
    recorded. Non-empty means someone edited the client file afterwards, and
    the values reported here are the client's — the ones it will actually
    send."""


def _read_cline(path: Path) -> DiscoveredClient | None:
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return None
    if not isinstance(data, dict):
        return None
    url = data.get("openAiBaseUrl")
    if not isinstance(url, str) or not url:
        return None
    info = data.get("openAiModelInfo")
    context = info.get("contextWindow") if isinstance(info, dict) else None
    return DiscoveredClient(
        client="cline",
        path=path,
        base_url=url,
        model=str(data.get("openAiModelId") or ""),
        api_key=str(data.get("openAiApiKey") or ""),
        context=context if isinstance(context, int) and not isinstance(context, bool) else None,
    )


def _read_aider(path: Path) -> DiscoveredClient | None:
    """Aider splits itself across three places: the model in a YAML file, the
    limits in a metadata JSON, and the URL and key in the environment."""
    try:
        conf = path.read_text(encoding="utf-8")
    except OSError:
        return None
    model = ""
    for line in conf.splitlines():
        if line.strip().startswith("model:"):
            model = line.split(":", 1)[1].strip()
            break
    if not model:
        return None

    context = None
    meta_path = path.parent / ".aider.model.metadata.json"
    if meta_path.exists():
        try:
            meta = json.loads(meta_path.read_text(encoding="utf-8"))
            entry = meta.get(model) if isinstance(meta, dict) else None
            if isinstance(entry, dict):
                value = entry.get("max_input_tokens")
                if isinstance(value, int) and not isinstance(value, bool):
                    context = value
        except (OSError, ValueError):
            context = None

    return DiscoveredClient(
        client="aider",
        path=path,
        base_url=os.environ.get("OPENAI_API_BASE", ""),
        # Aider is told `openai/<model>`; the server knows it without the prefix.
        model=model.split("/", 1)[-1],
        api_key=os.environ.get("OPENAI_API_KEY", ""),
        context=context,
        key_env_var="OPENAI_API_KEY",
    )


def _read_octofriend(path: Path) -> DiscoveredClient | None:
    """JSON5: unquoted keys and trailing commas, so json.loads cannot be used.

    A tolerant field scan is deliberate - this file is meant to be hand-edited,
    and refusing to read a config a user has legitimately customised would send
    them back to retyping the very values we are trying to recover.
    """
    try:
        text = path.read_text(encoding="utf-8")
    except OSError:
        return None

    def field_of(name: str) -> str:
        match = re.search(rf'{name}\s*:\s*"([^"]*)"', text)
        return match.group(1) if match else ""

    url = field_of("baseUrl")
    if not url:
        return None
    context_match = re.search(r"context\s*:\s*(\d+)", text)
    env_var = field_of("apiEnvVar") or "LOCAL_LLM_KEY"
    return DiscoveredClient(
        client="octofriend",
        path=path,
        base_url=url,
        model=field_of("model"),
        api_key=os.environ.get(env_var, ""),
        context=int(context_match.group(1)) if context_match else None,
        key_env_var=env_var,
    )


_READERS = (
    ("cline-settings.json", _read_cline),
    (".aider.conf.yml", _read_aider),
    ("octofriend.json5", _read_octofriend),
)


def _read_sidecar(path: Path) -> DiscoveredClient | None:
    """The record `join` leaves, which every client shares.

    Preferred over the client's own file because two of the three keep their
    base URL in the environment: on a fresh shell those configs name a model
    and nothing else, which is not enough to check anything.
    """
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return None
    if not isinstance(data, dict) or data.get("version") != SIDECAR_VERSION:
        return None
    url = data.get("base_url")
    if not isinstance(url, str) or not url:
        return None

    client = str(data.get("client") or "")
    env_var = str(data.get("key_env_var") or "")
    # The secret deliberately is not here. It stays where the client itself
    # looks for it: in the client's own file, or in the environment.
    api_key = os.environ.get(env_var, "") if env_var else ""
    if not api_key:
        own = next((r(path.parent / f) for f, r in _READERS if (path.parent / f).exists()), None)
        if own is not None:
            api_key = own.api_key

    context = data.get("context")
    return DiscoveredClient(
        client=client,
        path=path,
        base_url=url,
        model=str(data.get("model") or ""),
        api_key=api_key,
        context=context if isinstance(context, int) and not isinstance(context, bool) else None,
        key_env_var=env_var,
    )


def read_client_config(directory: Path | str = ".") -> DiscoveredClient | None:
    """Find a config this tool wrote and recover what the doctor needs.

    Returns None rather than raising: not finding one is an ordinary state on a
    laptop that has not been joined yet, and the caller has a better error to
    give than this function does.

    When both the sidecar and the client's own file are present they are
    **reconciled, and the client's file wins**. The sidecar records what `join`
    intended; the client file is what the client actually loads. Preferring the
    sidecar unconditionally meant a hand-edited `octofriend.json5` asking for
    131,072 tokens was checked as though it asked for 8,192 — so `check`
    reported "context agrees" for a client heading straight into a 400. Two
    copies of one fact, and nothing comparing them.
    """
    d = Path(directory)
    own = next(
        (r(d / f) for f, r in _READERS if (d / f).exists() and r(d / f) is not None),
        None,
    )

    sidecar = d / SIDECAR
    recorded = _read_sidecar(sidecar) if sidecar.exists() else None

    if recorded is None:
        # Covers a laptop joined before the sidecar existed, and one a user
        # assembled by hand.
        return own
    if own is None:
        return recorded

    drift = tuple(
        field
        for field, intended, actual in (
            ("context", recorded.context, own.context),
            ("model", recorded.model, own.model),
        )
        # A client file that does not carry a field at all is not disagreeing
        # about it; only a different value is drift.
        if actual is not None and actual != "" and intended != actual
    )
    if not drift:
        return recorded

    # Take the client's own values where it has them, but keep the sidecar's
    # base URL when the client keeps that in the environment and it is unset.
    return DiscoveredClient(
        client=own.client,
        path=own.path,
        base_url=own.base_url or recorded.base_url,
        model=own.model or recorded.model,
        api_key=own.api_key or recorded.api_key,
        context=own.context if own.context is not None else recorded.context,
        key_env_var=own.key_env_var or recorded.key_env_var,
        drift=drift,
    )
